{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oms.fullname" . }}-db
  labels:
    {{- include "oms.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
---
{{- if and .Values.shopify.webhookSecret (not .Values.shopify.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oms.fullname" . }}-shopify
  labels:
    {{- include "oms.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-secret: {{ .Values.shopify.webhookSecret | quote }}
{{- end }}
